import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MobileSidebar from "../components/MobileSidebar";
import SearchBar from "../components/SearchBar";
import { AccountDataProvider } from "../context/AccountDataContext";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Account Manager App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-[100vh] flex flex-col overflow-hidden">
        <AccountDataProvider>
          <nav className="min-h-16 flex items-center px-4 bg-primary">
            <MobileSidebar />
            <span className="font-semibold">Accounts</span>
            <SearchBar />
            <span />
          </nav>
          <section className="w-full flex overflow-hidden flex-1">
            <nav className="w-64 h-full overflow-y-auto overflow-x-hidden hidden md:block shadow-2xl"></nav>
            <div className="flex-3 overflow-y-auto overflow-x-hidden">
              <div className="bg-[#ebebeb] flex flex-col gap-6 p-6">{children}</div>
            </div>
          </section>
        </AccountDataProvider>
      </body>
    </html>
  );
}
