export { default as Plus } from "@/icons/Plus"
export { default as Checked } from "@/icons/Checked"
export { default as Cross } from "@/icons/Cross"
export { default as Delete } from "@//icons/Delete"
export { default as Edit } from "@//icons/Edit"
export { default as Tick } from "@//icons/Tick"